sheldontest/urls.py
from django.contrib import admin
from django.urls import path
from apitest import views
from product import proviews
from bug import bugviews
from set import setviews
from webtest import webviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', views.test),
    path('login/',views.login),
    path('home/',views.home),
    path('logout/',views.logout),
    path('product_manage/',proviews.product_manage),
    path('apitest_manage/',views.apitest_manage),
    path('apistep_manage/',views.apistep_manage),
    path('apis_manage/',views.apis_manage),
    path('bug_manage/',bugviews.bug_manage),
    path('set_manage/',setviews.set_manage),
    path('user/',setviews.set_user),
    path('webcase_manage/',webviews.webcase_manage),
    path('webcasestep_manage/',webviews.webcasestep_manage),
]

apitest/models.py
from product.models import Product
from django.db import models
class Apitest(models.Model):
    Product = models.ForeignKey('product.Product',on_delete=models.CASCADE,null=True)
    #关联产品ID,其中product是应用名,Product是product应用的表名
    apitestname = models.CharField('流程接口名称',max_length=64,null=True)
    apitestdesc = models.CharField('描述',max_length=64,null=True)
    apitester = models.CharField('测试负责人', max_length=16,null=True)  # 执行人
    apitestresult = models.BooleanField('测试结果',null=True)  # 流程接口测试结果
    create_time = models.DateTimeField('创建时间', auto_now=True)  # 创建时间-自动获取当前时间

    class Meta:
        verbose_name = '流程场景接口'
        verbose_name_plural = '流程场景接口'

    def __str__(self):
        return self.apitestname

class Apistep(models.Model):
    Apitest = models.ForeignKey(Apitest,on_delete=models.CASCADE,null=True) #关联接口ID
    apiname = models.CharField('接口名称',max_length=100,null=True)
    apiurl = models.CharField('url地址',max_length=200,null=True)
    REQUEEST_METHOD = (('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch'))
    # apiparamvalue = models.CharField('请求参数和值',max_length=800)#请求参数和值
    apiparamvalue = models.CharField('请求参数和值', max_length=800,null=True)#参数和值

    apimethod = models.CharField(verbose_name='请求方法',choices=REQUEEST_METHOD,default='get',max_length=200,null=True)#请求方法
    apiresult = models.CharField('预期结果',max_length=200,null=True)
    apistatus = models.BooleanField('是否通过',null=True)
    create_time = models.DateTimeField('创建时间',auto_now=True)
    def __str__(self):
        return self.apiname

class Apis(models.Model):
    Product = models.ForeignKey('product.Product', on_delete=models.CASCADE, null=True)
    apiname = models.CharField('接口名称',max_length=100,null=True)#接口标题
    apiurl = models.CharField('url地址',max_length=200,null=True)#地址
    # producter = models.CharField('产品负责人',max_length=200,null=True)
    apiparawvalue = models.CharField('请求参数和值',max_length=800)
    REQUEST_METHOD =(('0','get'),('1','post'),('2','put'),('3','delete'),('4','patch'))
    apimethod = models.CharField(verbose_name='请求方法',choices=REQUEST_METHOD,default='0',max_length=200,null=True)
    apiresult = models.CharField('预期结果',max_length=200,null=True)
    apistatus = models.BooleanField('是否通过',null=True)
    create_time = models.DateTimeField('创建时间', auto_now=True)
    class Meta:
        verbose_name = '单一场景接口'
        verbose_name_plural = '单一场景接口'
    def __str__(self):
        return self.apiname

bug/models.py
from django.db import models
from product.models import Product

class Bug(models.Model):
    Product = models.ForeignKey('product.Product',on_delete=models.CASCADE,null=True)
    bugname = models.CharField('bug名称',max_length=64,null=True)#bug名称
    bugdetail = models.CharField('详情',max_length=200,null=True)#详情
    BUG_STATUS = (('激活','激活'),('已解决','已解决'),('已关闭','已关闭'))
    bugstatus = models.CharField(verbose_name='解决状态',choices=BUG_STATUS,default='激活',max_length=200,null=True)#解决状态
    BUG_LEVEL = (('1','1'),('2','2'),('3','3'))
    buglever = models.CharField(verbose_name='严重程度',choices=BUG_LEVEL,default='3',max_length=200,null=True)#严重程度
    bugcreater = models.CharField('创建人',max_length=200,null=True)
    bugassign = models.CharField('分配给',max_length=200,null=True)
    create_time = models.DateTimeField('创建时间',auto_now=True)

    class Meta:
        verbose_name = '缺陷管理'
        verbose_name_plural = '缺陷管理'

    def __str__(self):
        return self.bugname

product/models.py
from django.db import models
class Product(models.Model):
    productname = models.CharField('产品名称',max_length=64)
    productdesc = models.CharField('产品描述',max_length=200)
    producter = models.CharField('产品负责人',max_length=200)
    cerate_time = models.DateTimeField('创建时间',auto_now=True)

    class Meta:
        verbose_name = '产品管理'
        verbose_name_plural = '产品管理'

    def __int__(self):
        return self.productname

set/models.py
from django.db import models
class Set(models.Model):
    setname = models.CharField('系统名称',max_length=64,null=True)
    setvalue = models.CharField('系统设置',max_length=200,null=True)
    class Meta:
        verbose_name = '系统设置'
        verbose_name_plural = '系统设置'
    def __str__(self):
        return self.setname

webtest/models.py
from django.db import models

class Webcase(models.Model):
    Product = models.ForeignKey('product.Product',on_delete=models.CASCADE,null=True)
    webcasename = models.CharField('用例名称',max_length=200)
    webtestresule = models.BooleanField('测试结果')
    create_time = models.DateTimeField('创建时间',auto_now=True)
    class Meta:
        verbose_name = 'web测试用例'
        verbose_name_plural = 'web测试用例'
    def __str__(self):
        return self.webcasename

class Webcasestep(models.Model):
    Webcase = models.ForeignKey(Webcase,on_delete=models.CASCADE)
    webcasename = models.CharField('测试用例标题',max_length=200)
    webteststep = models.CharField('测试用例步骤',max_length=200)
    webtestbojname = models.CharField('测试对象名称描述',max_length=200)
    webfindmethod = models.CharField('定位方式',max_length=200)
    webevelement = models.CharField('控件元素',max_length=800)
    weboptmethod = models.CharField('操作方法',max_length=200)
    webtestdata = models.CharField('测试数据',max_length=200,null=True)
    webassertdata = models.CharField('验证数据',max_length=200)
    webtestresule = models.BooleanField('测试结果')
    creata_time = models.DateTimeField('创建时间',auto_now=True)

    def __str__(self):
        return self.webcasename

apitest/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.contrib.auth import authenticate,login
from apitest.models import Apitest,Apistep,Apis
def test(request):
    return HttpResponse('hello test')


def login(request):
    if request.POST:
        username = password = ''
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            request.session['user'] = username
            response = HttpResponseRedirect('/home/')
            return response
        #  return redirect('/')
        else:
            return render(request, 'login.html', {'error': 'username or password error'})

    return render(request, 'login.html')


def home(request):
    return render(request,'home.html')

def logout(request):
    auth.logout(request)
    return render(request,'login.html')

@login_required
def apitest_manage(request):
    apitest_list = Apitest.objects.all()#读取所有的流程接口
    username = request.session.get('user','')#读取浏览器登录session
    #定义流程接口数据的变量并返回前端
    return render(request,'apitest_manage.html',{'user':username,'apitests':apitest_list})

@login_required
def apistep_manage(request):
    username = request.session.get('user','')
    apistep_list = Apistep.objects.all()
    return render(request,'apistep_manage.html',{'user':username,"apisteps":apistep_list})

@login_required
def apis_manage(request):
    username = request.session.get('user','')
    apis_list = Apis.objects.all()
    return render(request,'apis_manage.html',{'user':username,"apiss":apis_list})

set/views.py
from django.shortcuts import render

# Create your views here.

apitest/templates/apis_manage.html
<html lang="zh-CN">
    <head>
        <title>产品自动化测试管理平台</title>
    </head>
    <body role="document">
        <!--导航栏-->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class='navbar-brand' href="#">产品自动化测试管理平台</a>
                </div>
                <div id='navbar' class="collapse navbra-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/apis_manage/">单一接口测试</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">{{user}}</a></li>
                        <li><a href="#">退出</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!--单一接口测试用例-->
        <div class="row" style="padding-top: 20px">
            <div class="col-md-11">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th><th>单一产品接口测试用例名称</th><th>URL地址</th><th>参数=值</th><th>方法</th><th>预期结果</th><th>测试结果</th><th>时间</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for apis in apiss %}

                    
                        <tr>
                            <td>{{apis.id}}</td>
                            <td>{{apis.Product.productname}}</td>
                            <td>{{apis.apiname}}</td>
                            <td>{{apis.apiname}}</td>
                            <td>{{apis.url}}</td>
                            <td>{{apis.apiparawvalue}}</td>
                            <td>{{apis.apimethod}}</td>
                            <td>{{apis.apiresule}}</td>
                            <td>{{apis.apistatus}}</td>
                            <td>{{apis.create_time}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>

apitest/templates/apistep_manage.html
<html lang="zh-CN">
    <head>
        <title>自动化测试平台</title>
    </head>
    <body role="document">
        <!--导航栏-->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class='navbar-brand' href="#">自动化测试平台</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/apitest_namage/">流程接口测试</a></li>
                        <li class="active"><a href="/apitest_namage">流程接口测试步骤</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">{{user}}</a></li>
                        <li><a href="/logout/">退出</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!--流程接口测试步骤-->
        <div class="row" style="padding-top: 20px">
            <div class="col-ma-11">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>所属产品</th><th>所属用例</th><th>步骤</th><th>地址</th><th>参数=值</th><th>方法</th><th>预期结果</th><th>测试结果</th><th>执行时间</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for apistep in apisteps %}
                        <tr>
                            <td>{{apistep.Apitest.Product.productname}}</td>
                            <td>case_{{apistep.Apitest.id}}:{{apistep.Apitest.apitestname}}</td>
                            <td>{{apistep.Apistep.apistep}}:{{apistep.apiname}}</td>
                            <td>{{apistep.apiurl}}</td>
                            <td>{{apistepapiparamvalue}}</td>
                            <td>{{apistep.apimethod}}</td>
                            <td>{{apistep.apiresult}}</td>
                            <td>{% if apistep.apistatus == 1 %}
                                <a style="color: green">{{paistep.apistatus}}</a>
                                {% else %}
                                <a style="color: red">{{paistep.apistatus}}</a>
                                {% endif %}
                            </td>
                            <td>{{apistep.create_time}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>        
    </body>
</html>

apitest/templates/apitest_manage.html
<html lang = 'zh-CN'>
    <head>
        <title>自动化测试平台</title>
    </head>
    <body role="document">
        <!--导航栏-->
        <nav class='nav navbar-inverse navbar-fixed-top'>
            <div class="container">
                <div class="navbar-header">
                    <a class='navbar-brand' href="#">自动化测试平台</a>
                </div>
                <div id="navbar" class='collapse navbar-collapse'>
                    <ul class="nav navbar-nav">
                        <li class='active'><a href="#">流程接口测试</a></li>
                        <li><a href="#">流程接口测试步骤</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">{{user}}</a></li>
                        <li><a href="/logout/">退出</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!--流程接口列表-->
        <div class="row" style="padding-top: 20px">
            <div class="col-md-11">
                <thead>
                    <tr>
                        <th>ID</th><th>流程接口测试用例</th><th>流程接口描述</th><th>测试负责人</th><th>测试结果</th><th>测试用例步骤</th>
                    </tr>
                </thead>
                <tbody>
                    {% for apitest in apitests %}
                    <tr>
                        <td>{{ apitets.id}}</td>
                        <td>{{ apitets.Product.productname}}</td>
                        <td>{{ apitets.apitestname}}</td>
                        <td>{{ apitets.apitestdesc}}</td>
                        <td>{{ apitets.apitester}}</td>
                        <td>{{ apitets.apitestresult}}</td>
                        <td>{{ apitets.Apistep.apiteststep}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </div>
        </div>
    </body>
</html>

apitest/templates/home.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <title>自动化测试平台</title>
</head>
<body>
<ul>
    <u1 class = 'nav navbar-nav navbar-right'></u1>
    <li>欢迎<a href="#">{{ user }}</a>来到胡冰忠的自动化测试平台</li>
    <li><a href="/logout/">退出</a> </li>
</ul>
</body>
</html>

apitest/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Conten-Type" content="text/html; charset = utf-8">
    <title>登录</title>
</head>
<body>
    <h1>login</h1>
    <form method = "post" action = "/login/">
    {% csrf_token %}
    <br> <input name = "username" type = "text" placeholder = "用户名">
    <br> <input name = "password" type = "password" placeholder = "密码">
    {{ error }}<br>
    <br> <button id = "submit" type="submit">提交</button>
    </form>
</body>
<html>

webtest/templates/webcase_manage.html
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>产品自动化测试管理平台</title>
   <link href="../static/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
   
   
   
   <script type="text/javascript" src="/admin/jsi18n/"></script>
   
   <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
   <script type="text/javascript" src="/static/admin/js/core.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
   <script type="text/javascript" src="/static/admin/js/actions.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
   
   
       
   <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
       
   <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
       
   
   
   <meta name="robots" content="NONE,NOARCHIVE" />
   
    </head>
    <body role="document">
    <!-- 导航栏-->
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <div class="container">
   <li class="active"><a style='color:white' href="/apis_manage/">单一接口</a></li> 
   &nbsp;&nbsp;&nbsp;&nbsp;
   <li><a style='color:white' href="/apitest_manage/">流程接口</a></li>
   &nbsp;&nbsp;&nbsp;&nbsp;
   <li class="active"><a style='color:white' href="/appcase_manage/">app用例</a></li>
   &nbsp;&nbsp;&nbsp;&nbsp;
   <li class="active"><a style='color:white' href="/webcase_manage/">web用例</a></li>
   &nbsp;&nbsp;&nbsp;&nbsp;
    <ul class="nav justify-content-center">  
   
   </ul>
   <ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
   <li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
   <li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
   </ul>
    </div>
    </nav>
   
   <!-- 搜索栏-->
   <div class="page-header" style="padding-top: 0px;">
   <form class="navbar-form" method="get" action="/websearch/"> 
   {% csrf_token %}     
   <input type="search" name="webcasename" placeholder="名称" required>  
   <button type="submit">搜索</button>  
   <!-- 增加web测试用例-->
   <div style="float:right;width:65%">
   
   <select name="Webcase" id="id_Webcase">
   <option value="" selected>----web测试用例----</option>
   </select>
   <a class="related-widget-wrapper-link change-related" id="change_id_Webcase" data-href-template="/admin/webtest/webcase/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
   <img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
   </a>
   <a class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="/admin/webtest/webcase/add/?_to_field=id&amp;_popup=1" title="增加另一个 测试用例">
   <img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
   </a>  
   </form>
   </div>
   
    <!-- web测试用例列表-->
    <div class="row" style="padding-top: 20px;">
    <div class="col-md-12">
    <table class="table table-striped">
    <thead>
    <tr>
    <th>ID</th><th>产品</th><th>用例名称</th><th>结果</th><th>负责人</th><th>时间</th><th>查看</th><th>编辑</th><th>删除</th>
    </tr>
    </thead>
    <tbody>
    {% for webcase in webcases %}
    <tr>
    <td>{{ webcase.id }}</td>
    <td>{{ webcase.Product.productname }}</td>
    <td>{{ webcase.webcasename }}</td>
    <td>{{ webcase.webtestresult }}</td>
    <td>{{ webcase.webtester }}</td> 
    <td>{{ webcase.create_time }}</td> 
   <td><a href="{% url "webcasestep_manage" %}?webcase.id={{ webcase.id  }} "><img src="/static/admin/img/icon-yes.svg"/></a></td> 
   <td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="../admin/webtest/webcase/{{ webcase.id  }}/change/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-changelink.svg"/></a></td>
   <td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="../admin/webtest/webcase/{{ webcase.id  }}/delete/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-deletelink.svg"/></a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
   
   
   <!--统计和翻页功能-->
   <span style="position:absolute; left:600px; bottom:30px;">   {# 把翻页功能固定显示在右下角#}
   <div style="position:absolute; right:950px; bottom:25px; width:100px;">
   共:{{ webcasecounts }}条记录 {# 前端读取定义的变量#}
   </div>
   <div class="container">
       <ul class="pagination" id="pager">
             {# 上一页链接开始#}
           {% if webcases.has_previous %}
               {#  如果有上一页则正常显示上一页链接#}
               <li class="previous"><a href="/webcase_manage/?page={{ webcases.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
           {% else %}
               <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
           {% endif %}
           {# 上一页链接开始#}
           
           {% for num in webcases.paginator.page_range %}
            
               {% if num == currentPage %}
                   <li class="item active"><a href="/webcase_manage/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#} 
               {% else %}
                   <li class="item"><a href="/webcase_manage/?page={{ num }}">{{ num }}</a></li>
               {% endif %}
           {% endfor %}
           
           {# 下一页链接开始#}
           {% if webcases.has_next %} {#  如果有下一页则正常显示下一页链接#}
               <li class="next"><a href="/webcase_manage/?page={{ webcases.next_page_number }}">下一页</a></li>
           {% else %}
               <li class="next disabled"><a href="#">下一页</a></li>
           {% endif %}
           {# 下一页链接结束#}
       </ul>
   </div>
   
    </body>
    </html>
    

webtest/templates/webcasestep_manage.html
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>产品自动化测试管理平台</title>
   <link href="../static/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
   
   
   
   <script type="text/javascript" src="/admin/jsi18n/"></script>
   
   <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
   <script type="text/javascript" src="/static/admin/js/core.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
   <script type="text/javascript" src="/static/admin/js/actions.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
   
   <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
   
   
       
   <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
       
   <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
       
   
   
   <meta name="robots" content="NONE,NOARCHIVE" />
   
    </head>
    <body role="document">
    <!-- 导航栏-->
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <div class="container">
   <li class="active"><a style='color:white' href="/apis_manage/">单一接口</a></li> 
   &nbsp;&nbsp;&nbsp;&nbsp;
   <li><a style='color:white' href="/apitest_manage/">流程接口</a></li>
   &nbsp;&nbsp;&nbsp;&nbsp;
   <li class="active"><a style='color:white' href="/appcase_manage/">app用例</a></li>
   &nbsp;&nbsp;&nbsp;&nbsp;
   <li class="active"><a style='color:white' href="/webcase_manage/">web用例</a></li>
   &nbsp;&nbsp;&nbsp;&nbsp;
    <ul class="nav justify-content-center">  
   
   </ul>
   <ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
   <li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
   <li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
   </ul>
    </div>
    </nav>
   
   <!-- 搜索栏-->
   <div class="page-header" style="padding-top: 0px;">
   <form class="navbar-form" method="get" action="/websearch/"> 
   {% csrf_token %}     
   <input type="search" name="webcasename" placeholder="名称" required>  
   <button type="submit">搜索</button>  
   <!-- 增加web测试用例-->
   <div style="float:right;width:65%">
   
   <select name="Webcase" id="id_Webcase">
   <option value="" selected>----web测试用例----</option>
   </select>
   <a class="related-widget-wrapper-link change-related" id="change_id_Webcase" data-href-template="/admin/webtest/webcase/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
   <img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
   </a>
   <a class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="/admin/webtest/webcase/add/?_to_field=id&amp;_popup=1" title="增加另一个 测试用例">
   <img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
   </a>  
   </form>
   </div>
   
    <!-- web测试用例列表-->
    <div class="row" style="padding-top: 20px;">
    <div class="col-md-12">
    <table class="table table-striped">
    <thead>
    <tr>
    <th>ID</th><th>产品</th><th>用例名称</th><th>结果</th><th>负责人</th><th>时间</th><th>查看</th><th>编辑</th><th>删除</th>
    </tr>
    </thead>
    <tbody>
    {% for webcase in webcases %}
    <tr>
    <td>{{ webcase.id }}</td>
    <td>{{ webcase.Product.productname }}</td>
    <td>{{ webcase.webcasename }}</td>
    <td>{{ webcase.webtestresult }}</td>
    <td>{{ webcase.webtester }}</td> 
    <td>{{ webcase.create_time }}</td> 
   <td><a href="{% url "webcasestep_manage" %}?webcase.id={{ webcase.id  }} "><img src="/static/admin/img/icon-yes.svg"/></a></td> 
   <td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="../admin/webtest/webcase/{{ webcase.id  }}/change/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-changelink.svg"/></a></td>
   <td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="../admin/webtest/webcase/{{ webcase.id  }}/delete/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-deletelink.svg"/></a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
   
   
   <!--统计和翻页功能-->
   <span style="position:absolute; left:600px; bottom:30px;">   {# 把翻页功能固定显示在右下角#}
   <div style="position:absolute; right:950px; bottom:25px; width:100px;">
   共:{{ webcasecounts }}条记录 {# 前端读取定义的变量#}
   </div>
   <div class="container">
       <ul class="pagination" id="pager">
             {# 上一页链接开始#}
           {% if webcases.has_previous %}
               {#  如果有上一页则正常显示上一页链接#}
               <li class="previous"><a href="/webcase_manage/?page={{ webcases.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
           {% else %}
               <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
           {% endif %}
           {# 上一页链接开始#}
           
           {% for num in webcases.paginator.page_range %}
            
               {% if num == currentPage %}
                   <li class="item active"><a href="/webcase_manage/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#} 
               {% else %}
                   <li class="item"><a href="/webcase_manage/?page={{ num }}">{{ num }}</a></li>
               {% endif %}
           {% endfor %}
           
           {# 下一页链接开始#}
           {% if webcases.has_next %} {#  如果有下一页则正常显示下一页链接#}
               <li class="next"><a href="/webcase_manage/?page={{ webcases.next_page_number }}">下一页</a></li>
           {% else %}
               <li class="next disabled"><a href="#">下一页</a></li>
           {% endif %}
           {# 下一页链接结束#}
       </ul>
   </div>
   
    </body>
    </html>